title: Reinos del Hierro
description: Referencia en español para Iron Kingdoms Requiem
theme: jekyll-theme-slate
markdown: kramdown

# Configuración del sitio
baseurl: ""
url: "https://rdh.ludobermejo.es"

# Excluir archivos innecesarios
exclude:
  - README.md
  - CLAUDE.md
